In [ ]:
from data_loader_manager.data_loader_okvqa import DataLoaderOKVQA
from utils.config_system import get_config_from_json, process_config
import argparse
from easydict import EasyDict
#from data_loader_manager.data_loader_wrapper import DataLoaderWrapper

In [ ]:
jsonfile = '/Users/tonyyan/Desktop/Tony_VQA/Tony-VQA/configs/okvqa/DPR1.jsonnet'
config, config_dict = get_config_from_json(jsonfile)
args = argparse.Namespace(config=jsonfile, reset='your_value', mode='your_value', 
                           experiment_name='your_value', modules=[], tags=[], 
                           test_batch_size=-1, test_evaluation_name='', opts=[])

# Now pass this mock namespace to process_config
config = process_config(args)

In [ ]:

dataloader = DataLoaderOKVQA(config)
dataloader.build_dataset()

In [15]:
import torch
import torch.nn as nn

# Randomly generating output and label tensors
output = torch.randn(8, 32)  # Random logits for a batch of 8 items and 16 classes
label = torch.randint(0, 16, (8,))  # Random true classes for each item in the batch
#print(output)
#print(label)
# Cross-Entropy Loss
criterion = nn.CrossEntropyLoss()
loss = criterion(output, label)
print(loss)

# Printing the loss
print(loss.item())  # .item() is used to get the scalar value from the tensor


tensor(4.6269)
4.6268815994262695


In [5]:
import pickle

In [6]:
with open('img.pkl', 'rb') as f:
    img = pickle.load(f)

In [18]:
import torch
import torch.nn as nn
embedding_dim = 768
batch_size = 8
# Example embeddings for a question-image pair and a document
# Let's assume these embeddings are obtained from their respective encoders
Q = torch.randn(24, embedding_dim)  # Embeddings for question-image pair (size l_Q x embedding_dim)
D = torch.randn(16, embedding_dim)  # Embeddings for document (size l_D x embedding_dim)
intervalq = 24//batch_size
intervald = 16//batch_size
# Calculate the relevance score R(q, d)
# Using broadcasting to compute the dot product between each pair of embeddings
batch_score = torch.zeros(batch_size)
for i in range(batch_size):
    dot_products = torch.matmul(Q[i*intervalq:(i+1)*intervalq-1], D[i*intervald:(i+1)*intervald-1].T)  # Resulting shape will be l_Q x l_D
    max_dot_products = torch.max(dot_products, dim=1).values
    relevance_score = torch.sum(max_dot_products)
    batch_score[i] = relevance_score
print(batch_score)
# Find the max of dot products along the document dimension


# Sum over the question-image pair embeddings to get the final relevance score



tensor([ -1.5885,  29.6192,   1.1034,  -8.0993, -43.5419,   5.2552, -51.0941,
        -15.4133])


In [19]:
a = torch.randn(4, 4)
b = a.reshape(2, 8)
print(a)
print(b)

tensor([[ 0.4435, -0.8074, -1.0993, -1.3970],
        [ 1.3275,  1.5936,  0.7492,  1.3592],
        [ 0.3169, -0.8718, -1.2062,  2.0249],
        [-0.3374, -0.0322, -0.5785, -1.0548]])
tensor([[ 0.4435, -0.8074, -1.0993, -1.3970,  1.3275,  1.5936,  0.7492,  1.3592],
        [ 0.3169, -0.8718, -1.2062,  2.0249, -0.3374, -0.0322, -0.5785, -1.0548]])
